### ISSUE TITLE
There is a problem with installing of new version of this package from npm

### ISSUE THREAD

**Issue by pyxarez** [CrazySquirrel/EverCookie#5]
It looks like lib/EverCookie.js does not compile after installing of new version of this package(everything works just fine with 1.0.21 version)

**Comment by CrazySquirrel** [comment]
@pyxarez It's really strange. Because it seems that there is a new version in npm. Can you check if there are changes in node_moduels after upgrading and reinstalling new version of EverCookie? Maybe you have to run something like npm upgrade or yarn upgrade.

**Comment by pyxarez** [comment]
Yea, new version appeared in npm, but there is no way to install it
Every try to install/upgrade from previous version just breaks with the same error
Debug log in attachments
[2018-03-21T08_48_40_538Z-debug.log](https://github.com/CrazySquirrel/EverCookie/files/1832511/2018-03-21T08_48_40_538Z-debug.log)

**Comment by CrazySquirrel** [comment]
@pyxarez I think the problem is that there are no js files in the new package, only ts files. I'm not sure if it's a bug or not, but I'll check and release a new version, if it's.

**Comment by CrazySquirrel** [comment]
@pyxarez I think I fixed that bug. But I clearly need to fix something in ci.

**Comment by pyxarez** [comment]
@CrazySquirrel, you're right! Now it installs just fine
For the end i have to point out that `getItem` under the requestAnimationFrame spends huge amount of cpu resources, especially on slow devices(20-30% sometimes)
