### ISSUE TITLE
ERROR TypeError: EverCookie_1.default is not a constructor

### ISSUE THREAD

**Issue by jatpat** [CrazySquirrel/EverCookie#6]
application compiles without issue but I am getting following error while opening url(http://localhost:4200/) in browser.

> ERROR TypeError: EverCookie_1.default is not a constructor
    at AppComponent.ngOnInit (app.component.ts:19)
    at checkAndUpdateDirectiveInline (core.js:12411)
    at checkAndUpdateNodeInline (core.js:13935)
    at checkAndUpdateNode (core.js:13878)
    at debugCheckAndUpdateNode (core.js:14771)
    at debugCheckDirectivesFn (core.js:14712)
    at Object.eval [as updateDirectives] (AppComponent_Host.ngfactory.js? [sm]:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14697)
    at checkAndUpdateView (core.js:13844)
    at callWithDebugContext (core.js:15098)

**_Following is my code:_**

```
import { Component, OnInit } from '@angular/core';
import EverCookie from 'EverCookie';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app';

  ngOnInit() {
    const objEverCookie = new EverCookie("device");
  }
}
```

**Comment by CrazySquirrel** [comment]
I'll check it later, but If you using Angular make sure that you import/require EverCookie.ts and that your webpack doesn't exclude node_modules/EverCookie. Also try to assemble it with source maps to get more informative error.

**Comment by jatpat** [comment]
Thanks, working for more error details.

**Comment by jatpat** [comment]
Hi Sergei Iastrebov,

The issue is resolved. By default, the project was created with angular/CLI version 1.\*.\*   I updated it to latest 6.0.8 and it is working now.

**Here is output:**
Cookie value found only in Local Storage, Session Storage.   Cookie value was not found in normal website cookie storage.   

Can you guide me why it is not storing in website Cookies storage?

**Following is my code:**

```
"use strict";
import { Component, OnInit } from "@angular/core";
import EverCookie from "EverCookie";

let checkSupport:boolean = true;
let key:string = "key";
let value:string = "test cookie value";

const LocalEverCookie = new EverCookie("test");
//LocalEverCookie.setItem(checkSupport, key, value);
const v = LocalEverCookie.getItem(checkSupport, key);
console.info(v);
const t = LocalEverCookie.getKeys(checkSupport);
console.info(t);
```

**Comment by CrazySquirrel** [comment]
Try to call document.cookie from console at the same browser tab, where you execute your code, you might see data there. Or try to select right domain and update cookie list in development panel.
Also you can execute 
```
(
        typeof document === "object" &&
        typeof document.cookie === "string"
)
```
 to check is cookie storage supported in current environment.

**Comment by jatpat** [comment]
Hi,

I checked but it simply returns "" (blank string).

**Following is output with cookie key name "test":**

![image](https://user-images.githubusercontent.com/6779382/41408021-fa54702a-6fee-11e8-88c7-84869757c582.png)

![image](https://user-images.githubusercontent.com/6779382/41409366-8c93713a-6ff3-11e8-8a61-84994f47e615.png)




**Following is output with domain:**

![image](https://user-images.githubusercontent.com/6779382/41409193-fb4cb2ea-6ff2-11e8-82b5-5b65c6bc69d7.png)

![image](https://user-images.githubusercontent.com/6779382/41409899-6ac2507e-6ff5-11e8-9493-a5fe76dde8d7.png)

**Comment by CrazySquirrel** [comment]
@jatpat Hi, I found an error, cookies only worked for subdomains. I've fixed that.
